[package]
name = "threshold_crypto_ocaml_stubs"
authors = ["Vladimir Komendantskiy <komendantsky@gmail.com>"]
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
bincode = "1.2"
ocaml = "0.8.1"
rand = "0.6.5"
threshold_crypto = "0.3.2"
